### ISSUE TITLE
Document running a production server with pm2/nohup

### ISSUE THREAD

**Issue by tournament-of-shivs** [RanvierMUD/ranviermud#317]
The website explains installing and executing ./ranvier, but it lacks an actual manual on the intricacies of running a server. I was advised to use pm2 to maintain the server process on my VPS. I'm sure others could benefit from a crash course guide to basic server etiquette.

**Comment by seanohue** [comment]
Would a possible solution be to simply include pm2 as a dependency, with a default config? Or do we not want to be that opinionated?

**Comment by shawncplus** [comment]
While there isn't a full-on guide for each tool at least the docs mention PM2 and other server tools now
