### ISSUE TITLE
"up" and "down" not defined in coordinate rooms

### ISSUE THREAD

**Issue by MarchosiasM** [RanvierMUD/ranviermud#323]
### Description

While in coordinate based rooms, the full text of up and down fail when attempting to navigate

### Expected outcome

up should navigate up

down should navigate down

### Actual outcome

up returns "Huh?"

''

### Version of Ranvier

2.0 It hink

**Comment by shawncplus** [comment]
`Player.canGo` still has an old naive implementation of looking for exits that does not take coordinates into account, needs to be updated

**Comment by seanohue** [comment]
Seems that @nahilep ran into this issue as well. The coordinate rooms accept `n`, `s`, `u`, etc. but not the full directional name. `move north` or `walk north` work as well.

**Comment by shawncplus** [comment]
Fixed with getExits change
