### ISSUE TITLE
Add 'settings' type objects to Commands for customization

### ISSUE THREAD

**Issue by shawncplus** [RanvierMUD/ranviermud#325]
Commands currently lack a place to put extra data about them that bundles might want to set/access. Imagine there are `sit/sleep/stand` commands and the developer wants to stop certain commands from being used while the player is sleeping, there is currently no place to put that info.

### Details

Add a `config` property to `Command` defaulting to an empty object. Bundles will be free to place whatever data they want in there and access it via the `Command` instance retrieved from `CommandManager`

As part of this the current `requiredRole` should be moved to this new settings object and out of core

**Comment by tournament-of-shivs** [comment]
Wouldn't be better to keep a 'status' attribute on the character, and check to see if the character's status  allows for the command to be used?

**Comment by shawncplus** [comment]
That's two sides of the same coin. `Command` would have some "settings" property that a programmer could define a list of valid statuses and then the `Character` would have a current status property. The code for the check for whether a player can execute a command based on their given status, in my opinion, wouldn't happen in either the `Character` or the `Command` class. It'd happen wherever commands get executed, e.g., `input-events/commands.js` like

```js
if (command.config.allowedStatuses.includes(player.status)) { /* do stuff */ }
```

**Comment by shawncplus** [comment]
Implemented: `Command` now has a `metadata` property
