### ISSUE TITLE
Move CommandParser into ranvier-lib bundle

### ISSUE THREAD

**Issue by shawncplus** [RanvierMUD/ranviermud#330]
The `CommandParser` class in `src/` is currently very opinionated and people might mistake it being in `src/` for being unchangeable. Every other class that acts as an example implementation currently exists in the bundles.

1. Move `CommandParser` into `ranvier-lib/`
2. Update all bundle commands' references to the parser
3. Remove unused parser include inside `src/Character.js`
4. Update docs relating to command parser

**Comment by nahilep** [comment]
A little thing on the command parser I find confusing, but it is nowhere used yet, so it has never been an issue:

the `originalCommand` value of the first move-check is the translated value (e.g. `northeast`) and not the command originally triggering the move (e.g. `ne`)

**Comment by nahilep** [comment]
More places with unused CommandParser that is included:
* bundles/ranvier-commands/commands/config.js
* bundles/ranvier-combat/commands/pvp.js
* bundles/ranvier-combat/commands/kill.js

**Comment by shawncplus** [comment]
Implemented in `npmified` and documented
