### ISSUE TITLE
Refactor existing areas to use readable ids rather than numeric

### ISSUE THREAD

**Issue by seanohue** [RanvierMUD/ranviermud#339]
### Description

Having numeric IDs such as `limbo:1` and `craft:2` makes it very difficult to tell exactly what the room/item/NPC is that is being referenced.

This makes it tough for beginning builders to work with the existing areas, and also leads to the misconception that IDs have to be numeric.

### Expected outcome

An ID for an entity reference should be at least somewhat human readable, such as `craft:greenplant`.

### Actual outcome

Many IDs are not human-friendly and consist of a single-digit number.

### Steps to reproduce

Look at the default bundle item definitions.

### Version of Ranvier
2.0.0 (and all other versions thus far)

**Comment by Vindexus** [comment]
I can take a crack at this.

**Comment by Vindexus** [comment]
https://github.com/shawncplus/ranviermud/pull/340

**Comment by seanohue** [comment]
I think it looks solid -- I don't have permissions to merge it but I did look over it and didn't see any issues.

**Comment by shawncplus** [comment]
Closed in #340
