### ISSUE TITLE
Error when port 4000 is not available

### ISSUE THREAD

**Issue by oestrich** [RanvierMUD/ranviermud#358]
### Description
When port 4000 is already in use I get an error that doesn't direct me to that fact.

Port 4000:
```
/home/eric/prog/src/ranviermud/bundles/ranvier-telnet/node_modules/ranvier-telnet/index.js:347
      this.emit('error', error);
           ^

TypeError: this.emit is not a function
    at Server.TelnetServer.netServer.on.error (/home/eric/prog/src/ranviermud/bundles/ranvier-telnet/node_modules/ranvier-telnet/index.js:347:12)
```

Port 4001, on the other hand tells me its in use:
```
events.js:183         throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4001
```

### Expected outcome

I would expect the telnet port to raise a similar error to the websocket port.

### Actual outcome

See description above.

### Steps to reproduce

- Clone a fresh copy of Ranvier
- Have something else up on port 4000 (another copy of ranvier maybe.)
- `./ranvier`

### Version of Ranvier
`2.0.0` - a new clone of current `staging`

**Comment by nahilep** [comment]
Looks like this was fixed in ranvier-telnet already: https://github.com/shawncplus/ranvier-telnet/pull/2
An update to the latest version of ranvier-telnet should be enough. Unfortunatly I am unable to update this dependency.
