### ISSUE TITLE
When attempting to lower a positive attribute (e.g. from 5 to 3), Math.min forces it to 0 instead

### ISSUE THREAD

**Issue by Polatrite** [RanvierMUD/ranviermud#366]
**Describe the bug**
When you attempt to lower an attribute with a positive value to another non-zero positive value, Attribute.js:45 forces it to be set to 0 instead.

I have a feeling this is unintended due to some behavior around keeping the deltas in check?

**To Reproduce**

1. Create a new attribute, such as "POWAH" with a starting value of 5.
2. In regen.js (or a test command, somewhere else, etc.) decrement the value by 1 (by committing damage, or otherwise calling attribute.lower()
3. Check the value

**Expected behavior**
5 should be reduced to 4

**Actual behavior**
5 is instead reduced to 0

**Error logs**
If the server produced an error paste the log here

**Environment (please complete the following information):**
 - OS: Win10 Pro 64-bit
 - Node v10.12.0

**Comment by shawncplus** [comment]
This sounds like your base value is wrong. Make sure you're setting the base value to the max and then decreasing with `lowerAttribute`. You can look at the `favor` attribute used by the example paladin class which does exactly like you describe and does, in fact, lower by 1 per regen tick.

**Comment by shawncplus** [comment]
Haven't heard anything new on this, assuming no work needed
