### ISSUE TITLE
Equipment Slot Manager

### ISSUE THREAD

**Issue by ratacat** [RanvierMUD/ranviermud#378]
I've been thinking I wanted to write a Slot manager.  I'm curious if this is something you think would see as helpful @shawncplus, and if you had any input or thoughts on it.

My reasoning and motivations:
* It seems like leaving the slot to a string in each equipment definition could get convoluted with multiple builders over time
* I'd ultimately like to have a good base for rolling randomized equipment
* Customized equip / un-equip messages, which I'm currently doing in the Wear command.
* I'd like different races, classes, effects, or traits to modify a characters slots.

**Comment by seanohue** [comment]
@NamelessFaceless @ratacat Sounds like a good time to start a repo for this bundle/library and do some planning.

**Comment by NamelessFaceless** [comment]
@seanohue @ratacat Agreed. We could discuss this over on Slack more.

**Comment by shawncplus** [comment]
@ratacat I'm gonna close this issue, looks like y'all are going to create a different repo for this

**Comment by seanohue** [comment]
I made the repo here -- it is empty and the name is subject to change. I'll start on ideation for it tonight or tomorrow in the Issues section of the repo, but if you have feature requests before then, please submit them.

https://github.com/seanohue/paperdoll/

**Comment by seanohue** [comment]
Ideally I'd want it to be a ranvier bundle but also have parts of it be usable as an npm lib for non-Ranvier games.
