### ISSUE TITLE
3.0 - Help Files (YAML Directories) Not Loading After Data Handling Merge

### ISSUE THREAD

**Issue by digitalmisanthrope** [RanvierMUD/ranviermud#381]
This likely should be written into a pull request but GIT scares me and I'm more an ops guy than a dev guy so just wanted to document this issue somewhere.

**Describe the bug**
After data handling merges Ranvier was failing to launch due to being unable to locate the pathing for Help. 

**To Reproduce**
I verified that ranvier.json did have the correct pathing so I looked at the YAMLDirectoryDataSource.js and compared it to JSONDirectoryDataSource.js which appeared to work and be functionally identical. I was able to resolve the issue by replacing YAMLDirectoryDataSource.js with JSONDirectoryDataSource.js and change all references to JSON to YAML equivalents.

The major differences between the two appeared to be related async and fs.realpathSync(dirPath) versus just dirPath.

**Expected behavior**
Should launch as normal after these changes.

**Error logs**
(node:7011) UnhandledPromiseRejectionWarning: Error: No path for DataSource

   at YamlDirectoryDataSource.resolvePath (/home/ranviermud/ranvier/3.0/ranvier3.0-vanaheim/node_modules/ranvier-datasource-file/FileDataSource.js:20:13)

   at YamlDirectoryDataSource.fetchAll (/home/ranviermud/ranvier/3.0/ranvier3.0-vanaheim/node_modules/ranvier-datasource-file/YamlDirectoryDataSource.js:31:26)

   at EntityLoader.fetchAll (/home/ranviermud/ranvier/3.0/ranvier-core/src/EntityLoader.js:33:28)

   at BundleManager.loadHelp (/home/ranviermud/ranvier/3.0/ranvier-core/src/BundleManager.js:471:34)

(node:7011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:7011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Environment (please complete the following information):**
 - OS: 16.04
 - 10.15.0

**Comment by shawncplus** [comment]
Make sure to `npm update` in your ranvier repo. There was a fix that I published before I even announced the `npmified` merge to directory resolution for `YamlDirectoryDataSource`. IF that still doesn't work let me know in slack

**Comment by digitalmisanthrope** [comment]
NPM update seems to have resolved the issue. The usual workflow seems to now carry through without a hitch.
