### ISSUE TITLE
NPC Metadata is shared amongst instances of the same NPC

### ISSUE THREAD

**Issue by ratacat** [RanvierMUD/ranviermud#390]
**Describe the bug**
NPC Metadata appears to be shared amongst npcs that have the same entityID. 

**To Reproduce**
Load multiple instances of a single NPC, set some metadata after the fact, such as in an effect or behavior.

**Expected behavior**
I would expect it to be individual to the copy of that mob. So that you could set memory flags and other behavior things on individual npcs.

**Comment by ratacat** [comment]
So I tested this on a vanilla version of ranvier 3, and it seems to be fine. Individual rats, maintain their individual metadata. Not sure how I could have possibility messed it up. Going to have to look into it more. I was using a lot of npc effects at the time, I'm wondering if maybe that had something to do with it.

**Comment by ratacat** [comment]
There's actually more to this then I first realized. Even after using the Object.assign fix referenced above to ensure that character.metadata isn't shared...it still can happen in this way.

Add an effect to multiple npcs with the same entityReference. In that effect, create a new object under character metadata, for example..

`this.target.metadata.memory = new Object();`
`this.target.metadata.memory.hi = true;`

now check on the metadata for the other npcs with the shared entityReference. That new object will now be visible on all other NPCs sharing the entityReference.

**Comment by shawncplus** [comment]
Like I said in another ticket, `Object.assign` is not a valid fix for preventing shared objects because it does a shallow copy meaning that if metadata has nested objects those objects will still be shared. The only valid fix is to do `JSON.parse(JSON.stringify(object));`

**Comment by seanohue** [comment]
Seconding Shawn's comment above, though there are also library solutions as well: https://www.npmjs.com/package/lodash.clonedeep

**Comment by nahilep** [comment]
I am not sure if another dependency is really needed since `JSON.parse(JSON.stringify(object));` is perfectly doing it's job of _deep cloning_

**Comment by seanohue** [comment]
If it works, it works! Go for it.

**Comment by shawncplus** [comment]
Closed with ranviermud/core#86
