### ISSUE TITLE
slack invitation has expired

### ISSUE THREAD

**Issue by profy12** [RanvierMUD/ranviermud#394]
Slack invitation has expired.

Your mud system look awesome !

**Comment by shawncplus** [comment]
Site/readme should be updated, you can use this link now (https://join.slack.com/t/ranviermud/shared_invite/enQtODA1NTI4MTc5MjgyLWU1OTI2YTYxMTcwYTBjNmIyMzhmMWZmNTQ3ZmFiMWEwYjQ5N2MyYWQzODFhZDUwNmZiODE1ODVlNWE5NTlmYzU)
