### ISSUE TITLE
Refactor server commands

### ISSUE THREAD

**Issue by shawncplus** [RanvierMUD/ranviermud#85]
The server controls right now are really shitty and literally just bolted onto the end of the executable. Allow server commands to be part of a bundle as well and in the same format as normal commands. The only difference is that they can only be run from the server itself instead of from game. This includes things like `shutdown`, `restart`, `reload`, `saveall`, etc.

**Comment by marado** [comment]
Why shouldn't an admin  be able to run those commands from within the MUD?

**Comment by shawncplus** [comment]
In theory they could but the MVP is that they only run them from the server. Having them run the commands through the mud (specifically shutdown/restart) would require extra code to reattach sockets through the actual process shutting down which I haven't taken the time to look into yet

**Comment by stephenlcurtis** [comment]
Following up on my pullrequest (#90) I was thinking this would be some good next steps. Let me know what you think:

- Add flag to Server.js that serverOperation checks to make sure other operations aren't already in-flight.
- Add option to server shutdown to shutdown and process.exit()
- Store server operation timeouts as variables so you can call clearTimeout on them if you want to, maybe allowing for a "Cancel" server command?
- Separate out console input into its own class that extends EventEmitter and emits to the 'data' event (in the same way the Telnet Class does)
- Add arg to data event emitted to in Telnet and the new Console class that specifies where the command is coming from
- Add logic to command parser to separate server console commands from telnet commands to ensure players cant send server commands.
- Add command script for server commands to /bundles/core-commands/commands/ to be consistent with other commands

Notes on things I don't like about my checkin but don't have solution to yet:
- Countdown counter for player warn is a global variable
- BroadcastAt method for each player called via players.foreach, should we modify .players getter to include a method for players.broadcast that broadcasts to all players?
- Server.js instance is a scoped variable. Need to be able to access with state in tact from other modules. Possibly move Server variables outside class and make them globals, then make server methods static? I'm still relatively new to node so I'm not sure on the best design pattern to use here.

**Comment by shawncplus** [comment]
> BroadcastAt method for each player called via players.foreach

This bit

    this.GameState.PlayerManager.players.forEach(p => Broadcast.sayAt(p, `${warningStr} ${global.countdown/ 1000} SECONDS`));

Should be

    Broadcast.sayAt(this.GameState.PlayerManager, `${warningStr} ${global.countdown/1000} SECONDS`);

> Server.js instance is a scoped variable. Need to be able to access with state in tact from other modules.

`this.GameState = { server: this, ... }` should work just fine

**Comment by shawncplus** [comment]
The main `./ranvier` executable no longer has any commands, this can be implemented in bundle-land with server events
