### ISSUE TITLE
A Web API for building/administration

### ISSUE THREAD

**Issue by seanohue** [RanvierMUD/ranviermud#94]
Building a world viewer dashboard and eventually an editor, and thus a web API is necessary. Really just putting this issue out there so it's documented.

Needs:
[  ] A POST route for authentication.
[X] A GET request for each piece of world date (WIP).
[  ] POST routes to add new entities (NPCs, Rooms, etc) for builders.

Nice-to-have:
[  ] Ability to spawn copies of mobs or items.
[  ] Ability to edit existing entities, including players.
[  ] Ability to execute server commands (such as restart) or to use admin-related chat channels directly from the dashboard.

**Comment by jackjwilliams** [comment]
If there is one thing I have done before, it's build web apis. If you can give some more vision / guidance I can work on expanding the gets / posts / puts (potentially?). Specific questions / thoughts.

Based on my understanding of the architecture: 
Factories are specifically for easy creation / cloning (it does maintain it's own list)
Managers are really just for managing the list of entities (it does maintain it's own list). This is what most of the system uses.
BundleManager is the entry point that populates the managers, potentially using the factories.

The Data.js class is specifically for loading / saving player / account data.

1. I'm thinking something similar to Data.js, but specifically for Bundles, Areas, etc...
2. Do we want to support updating (puts?). Or maybe only POSTS for now?

It may be easiest to begin with areas. It should support naming (POST to create manifest.yml), and adding items / npcs / rooms. Quests are a kind of special since they are added by script.

**Comment by seanohue** [comment]
Right now it basically just has the GET requests for getting data. I think that there are a few features I'd want to have in a web API:

1. Creating new instances of already-defined mobs, items, etc. Relatively easy, would just need to hook into one of the factories as you mention.
2. Adding a new definition of a room, item, mob (which would then be able to be added to the game world via API #1. Adding a lot of custom scripting is out of scope but using the already-packaged behaviors should be easy.
3. There is already a WebInterface.js for handling the GET requests and the endpoints. I'm thinking maybe it could also hook into a WebEditor or WebBuilder class that would translate/delegate the POST or PUT requests to the factories/managers, and also handle saving new definitions to the filesystem as .yml -- which begs the question, where would it go? Would the POST request also specify a bundle name?

**Comment by jackjwilliams** [comment]
1. I like this idea, might be a good starting point.
2. Yep, but this also begs the questions: When do these newly created files get loaded? Upon reboot? Can it / should it hook into #113 (all these questions apply too)? 
3. In my experience, building a web API is itself an entire application. What I've done in the past is that the entire web API should be defined here (it IS the WebInterface) - GETS, POSTS, PUTS. Breaking it out into separate classes or module per route type (GETS vs POST / PUTS) could be cumbersome and difficult to maintain. I see a potentially routing structure like the following.

GET /bundles -> Get All Bundles (filter out all core-* bundles, except core-areas). Returns a list of bundle names (core-areas)
GET /bundles/{bundleName}/areas -> returns a list of areas the bundle contains [{id: 'limbo', Title: "Limbo", suggestedLevel: '1-9'}, {id: 'town-hall', Title: 'Town Hall', suggestedLevel: '1-60'}];
GET /bundles/{bundleName}/areas/{areaName} -> Could return the full graph of items from the area? (items, npcs, rooms). This might be a bit much.
GET /bundles/{bundleName}/areas/{areaName}/items -> Could return items.yml JSONified
GET /bundles/{bundleName}/areas/{areaName}/npcs-> Could return npcs.yml JSONified
GET /bundles/{bundleName}/areas/{areaName}/rooms-> Could return rooms.yml JSONified

GET /bundles/{bundleName}/areas/{areaName}/items/{itemId} -> Could return the item JSONified
GET /bundles/{bundleName}/areas/{areaName}/npcs/{npcId}-> Could return the NPC JSONified
GET /bundles/{bundleName}/areas/{areaName}/rooms/{roomId}-> Could return the room JSONified

POST /bundles -> creates a new folder under bundles
POST /bundles/{bundleName}/areas -> creates a new folder under bundles/{bundleName}/areas
POST /bundles/{bundleName}/areas/{areaName}/items -> Creates an item
POST /bundles/{bundleName}/areas/{areaName}/npcs -> Creates an npc
POST /bundles/{bundleName}/areas/{areaName}/rooms-> Creates a room

This could be expanded ad infinitum. If builders know basic scripting and the right listeners, we could one day allow posting item / npc / room scripts.

**Comment by jackjwilliams** [comment]
We could also namespace out the different "areas" (not to be confused with in-game areas) of functionality:

/api/builder (For world building - creating areas, rooms, items, quests)
/api/world (For spawning, modifying players / accounts, etc...).

I might have misunderstood your third point, this might go along with that.

**Comment by seanohue** [comment]
Sorry, I wasn't suggesting that the routes go in multiple separate classes. More that the WebInterface would pass the information received from POST requests onto another layer to be translated into the definition files. I might be overthinking this, and my brain is fried right now tbh but I like the work you've done in terms of brainstorming those routes. I'll have to take another look tomorrow.

As far as point 2 in your post, I think the newly created files would be saved to the filesystem, but the mobs or whatever could be immediately created via a factory since the definitions could also be stored in memory. So, the API call is made, the defs are store in memory and can be accessed by the factory, _and_ are saved in YAML so that the definitions persist across server instances. I hope I'm making myself clear but as I said, brain fried, so I'll come back to this tomorrow.

**Comment by seanohue** [comment]
That sounds like a good way to do it. Ideally I'd want to be able to build
a combination dashboard, administration, and builder/editor tool. It sounds
like you have way more API building experience so I look forward to working
with you on that -- I have more of a front-end background.


Sean O'Donohue
--
*Web Application Developer*
*GM NGI Onsite Team*

**Comment by shawncplus** [comment]
While a good idea it's one for a custom bundle, not provided by default
